version: '3.6'
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 51773:1972
      - 52773:52773
    environment:
      - DMN_ENV=dev
      - DMN_DATA_PATH=/home/irisowner/dev/data
    volumes:
      - ./:/home/irisowner/dev
      - ./dmn:/usr/irissys/csp/dmn
      - ./jdk-11.0.21+9-jre:/usr/lib/jvm/temurin-8-jdk-amd64
